name: adradio
description: RadioApintie app
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.2.6 <4.0.0'  # stay within Dart 3.x

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.10.0
  cupertino_icons: 1.0.8
  get: ^4.7.2

  faker: ^2.1.0

  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.15
#  audio_service: ^0.18.12
  rxdart: ^0.28.0
  audio_video_progress_bar: ^2.0.3

  flutter_screenutil: 5.9.3
  font_awesome_flutter: ^10.8.0
  country_code_picker: ^3.3.0
  material_design_icons_flutter: 7.0.7296
  get_storage: ^2.1.1
  logger: ^2.5.0
  pin_code_fields: 8.0.1
  intl: ^0.20.2
  image_picker: 1.1.2
  dotted_line: ^3.2.3
  iconsax: 0.0.8
  flutter_inappwebview: ^6.1.5
  flutter_spinkit: 5.2.1
  flutter_animate: ^4.5.2
  carousel_slider: ^5.0.0
  volume_controller: ^3.3.3
  percent_indicator: ^4.2.4
  flutter_staggered_grid_view: 0.7.0
  enhance_stepper: 1.0.1
  url_launcher: ^6.3.1
  audioplayers: ^6.4.0
  flutter_swipe_detector: 2.0.0
  google_fonts: ^6.2.1  # latest stable
  connectivity_plus: ^6.1.3
  http: ^1.3.0  # safe for Dart 3.2
  circular_menu: 4.0.0
  circular_widgets: 3.0.0
  dropdown_button2: 2.3.9
  lottie: ^3.3.1
  youtube_player_flutter: ^9.1.1
  simple_animations: ^5.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17
  archive: ^4.0.5  # Downgraded to avoid Dart 3.2 errors

  dynamic_languages:
    git:
      url: https://github.com/appdevsx/dynamic_languages
      ref: main
  rename: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  build_runner: any
  flutter_gen_runner: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app-launcher.png"

flutter_gen:
  output: lib/custom_assets/
  line_length: 80

flutter:
  uses-material-design: true
  assets:
    - assets/clipart/
    - assets/empty_animation.json
    - assets/icon/
    - assets/logo/
